services:
  pcsx2:
    image: lscr.io/linuxserver/pcsx2:latest
    container_name: pcsx2
    security_opt:
      - seccomp:unconfined # Melhora performance
    privileged: true # OBRIGATÓRIO para o controle e placa de vídeo funcionarem
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/games:/games
      - ${UMBREL_ROOT}/data/storage/downloads/ps2-games:/download-games
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5138:3001 # Acesso via navegador
    devices:
      - /dev/dri:/dev/dri # Acesso à placa de vídeo Intel
      - /dev/input:/dev/input # Acesso ao controle Bluetooth/USB
    shm_size: "10gb"
    restart: unless-stopped