version: '3.9'
services:
  steam:
    image: kasmweb/steam:1.18.0-rolling-daily
    container_name: kasmweb-steam
    ports:
      - '5140:6901'
    devices:
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp=unconfined
    privileged: true

    volumes:
      - /dev/input/:/dev/input/:ro
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/steam-games:/home/default/.steam:rw
    restart: unless-stopped
    environment:
      - VNC_PW=password
    shm_size: 512m
