version: "3.7"

services:
  ffmpeg:
    image: linuxserver/ffmpeg:arm64v8-latest
    container_name: ffmpeg
    volumes:
      - ./shared:/shared
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    entrypoint: ["/bin/bash"]
    command: ["-c", "while true; do sleep 30; done"]

  ffmpeg-api:
    image: gabrielsv01/ffmpeg-api:1.0.5
    container_name: ffmpeg-api
    environment:
      - PORT=5135
    ports:
      - "5135:5135"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared:/shared
    depends_on:
      - ffmpeg
    restart: unless-stopped
