services:
  retroarch:
    image: linuxserver/retroarch:1.21.0
    container_name: retroarch
    security_opt:
      - seccomp:unconfined
    privileged: true
    environment:
      - PUID=1000
      - PGID=995
      - TZ=America/Sao_Paulo
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=720
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/games:/games
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5140:3001
    devices:
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input
    shm_size: "10gb"
    restart: unless-stopped