services:
  picoclaw:
    image: gabrielsv01/pico-claw:v0.1.2
    container_name: picoclaw
    restart: unless-stopped
    # command: ["gateway", "--debug"]
    ports:
      - 5144:8080
    volumes:
      - ${APP_DATA_DIR}/workspace:/app/data/workspace
      # - ./workspace:/app/data/workspace
      # - ./config:/home/picoclaw/.picoclaw:ro
      - ${APP_DATA_DIR}/config:/home/picoclaw/.picoclaw:ro
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=production
      - PICOCLAW_GATEWAY_HOST=0.0.0.0
      - PICOCLAW_GATEWAY_PORT=8080