services:
  picoclaw-agent:
    image: sipeed/picoclaw:v0.1.2
    container_name: picoclaw-agent
    restart: unless-stopped
    ports:
      - 5144:8080
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      # - ./data:/app/data
      # - ./config:/root/.picoclaw:ro
      - ${APP_DATA_DIR}/data/config:/root/.picoclaw:ro
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=production
      - PICOCLAW_GATEWAY_HOST=0.0.0.0
      - PICOCLAW_GATEWAY_PORT=8080