version: "3.7"
services:
  telegram-webhook-api:
    image: gabrielsv01/telegram-webhook-api:1.0.13
    container_name: telegram-webhook-api
    environment:
      - PORT=5125
      - TELEGRAM_BOT_TOKEN=123
      - URI_BASE=/api/telegram
      - WEBHOOK_URL=https://ngrok-free.app
      - FORWARD_ENDPOINT=http://umbrel.local
      - NGROK_WEB_URL=http://umbrel.local:4040/status
    ports:
      - 5125:5125
    restart: unless-stopped

